version: "3"

services:
  redis:
    image: redis:alpine
    container_name: arthur_redis_db
    volumes:
      - ./database:/data
    ports:
      - 6380:6380
    expose:
      - 6380
    networks:
      - arthur-network
    restart: always

  backend:
    image: build.backend
    container_name: arthur_backend
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - backend/.env
    depends_on:
      - redis
    restart:
      on-failure

networks:
  arthur-network:
    name: arthur-network
    driver: bridge
